# -*- coding: utf-8 -*-
"""Primetrade.ai_assignment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Px_MUrLBdrTMoQhz7lXJuzQ6Y_8FIB0e

**Analyze Historical Trade Data**

**CREATING DATASET FROM THE PROVIDED .csv file.**
"""

import pandas as pd
import ast
import numpy as np
from scipy.stats import skew, kurtosis
from datetime import datetime
import matplotlib.pyplot as plt
import seaborn as sns


df = pd.read_csv("/content/TRADES_CopyTr_90D_ROI.csv")

# funcion string convert into a list of dictionaries.
def parse_trade_history(trade_history_str):
    if pd.isna(trade_history_str):
        return []
    try:
        return ast.literal_eval(trade_history_str) # use try and except for error handling.
    except (SyntaxError, ValueError):
        print(f"Error parsing: {trade_history_str}")
        return []

df['Trade_History'] = df['Trade_History'].apply(parse_trade_history)

# convert each list element into a separate row.
df_exploded = df.explode('Trade_History')


df_normalized = pd.json_normalize(df_exploded['Trade_History'])

df_exploded = df_exploded.reset_index(drop=True)  # reset index
df_normalized = df_normalized.reset_index(drop=True)

# concat the two column (features).
df_final = pd.concat([df_exploded['Port_IDs'], df_normalized], axis=1)

### convert 'time' to datetime objects.
df_final['time'] = pd.to_datetime(df_final['time'], unit='ms')

# Calculate daily returns/
df_final['daily_return'] = df_final.groupby('Port_IDs')['realizedProfit'].pct_change()

# convert time to datetime
df_final['time'] = pd.to_datetime(df_final['time'])

df_final = df_final.sort_values(by=['Port_IDs', 'time'])

## calculate daily cumulative profit,
df_final['cumulative_profit'] = df_final.groupby('Port_IDs')['realizedProfit'].cumsum()

# calculate daily returns (handling division by zero)
df_final['daily_return'] = df_final.groupby('Port_IDs')['cumulative_profit'].pct_change().fillna(0)

df_final.head()

"""**HANDEL MISSING VALUE.**"""

## handeling missing value
df_final.isnull().sum()

## handling missing value:
df_final['daily_return'].fillna(0, inplace=True)

# filling rest of column's Nan value to mode of that column:

df_final['time'].fillna(df_final['time'].mode()[0], inplace=True)
df_final['symbol'].fillna(df_final['symbol'].mode()[0], inplace=True)
df_final['side'].fillna(df_final['side'].mode()[0], inplace=True)
df_final['price'].fillna(df_final['price'].mean(), inplace=True)
df_final['fee'].fillna(df_final['fee'].mode()[0], inplace=True)
df_final['feeAsset'].fillna(df_final['feeAsset'].mode()[0], inplace=True)
df_final['quantity'].fillna(df_final['quantity'].mode()[0], inplace=True)
df_final['quantityAsset'].fillna(df_final['quantityAsset'].mode()[0], inplace=True)
df_final['realizedProfit'].fillna(df_final['realizedProfit'].mode()[0], inplace=True)
df_final['realizedProfitAsset'].fillna(df_final['realizedProfitAsset'].mode()[0], inplace=True)
df_final['baseAsset'].fillna(df_final['baseAsset'].mode()[0], inplace=True)
df_final['qty'].fillna(df_final['qty'].mode()[0], inplace=True)
df_final['positionSide'].fillna(df_final['positionSide'].mode()[0], inplace=True)
df_final['activeBuy'].fillna(df_final['activeBuy'].mode()[0], inplace=True)

df_final.info()

"""**This is Describtion of the Dataset(df_final)**"""

df_final.describe()

"""**SOME VISUALISATION FOR BETTER UNDERSTANDING.**"""

import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(8, 5))
sns.histplot(df_final['realizedProfit'], bins=50, kde=True)
plt.title("Distribution of Realized Profit")
plt.xlabel("Realized Profit")
plt.ylabel("Frequency")
plt.show()

plt.figure(figsize=(12, 6))
sns.boxplot(x=df_final['symbol'], y=df_final['realizedProfit'])
plt.title("Realized Profit Distribution per Asset")
plt.xlabel("Asset")
plt.ylabel("Realized Profit")
plt.xticks(rotation=45)
plt.show()

plt.figure(figsize=(12, 6))
sns.lineplot(data=df_final, x='time', y='cumulative_profit', hue='Port_IDs')
plt.title("Cumulative Profit Over Time")
plt.xlabel("Time")
plt.ylabel("Cumulative Profit")
plt.legend(title="Port_IDs", bbox_to_anchor=(1, 1))
plt.show()

"""# **analysis of trading performance metrics **"""

# calculate total positions
df_final['Total_Positions'] = df_final.groupby('Port_IDs')['symbol'].transform('count')

# calculate win positions
df_final['Win_Positions'] = df_final.groupby('Port_IDs')['realizedProfit'].transform(lambda x: (x > 0).sum())

#winning trades out of the total number of trades.
df_final['Win_Rate'] = df_final['Win_Positions'] / df_final['Total_Positions']

# calculate ROI
df_final['ROI'] = df_final['realizedProfit'] / df_final['quantity']

# drop from the highest profit.
df_final['Cumulative_Max'] = df_final.groupby('Port_IDs')['cumulative_profit'].transform(lambda x: x.cummax())
df_final['Drawdown'] = df_final['cumulative_profit'] - df_final['Cumulative_Max']
df_final['MDD'] = df_final.groupby('Port_IDs')['Drawdown'].transform(min)

# sharpe Ratio(higher sharpe Ratio means better return per unit of risk.)
df_final['Sharpe_Ratio'] = df_final.groupby('Port_IDs')['daily_return'].transform(lambda x: x.mean() / (x.std() + 1e-9))

# categarizes each trade as long/short open/close based on trading behavior,
def classify_trade(row):
    if row['side'] == 'BUY' and row['positionSide'] == 'LONG':
        return 'long_open'
    elif row['side'] == 'SELL' and row['positionSide'] == 'LONG':
        return 'long_close'
    elif row['side'] == 'SELL' and row['positionSide'] == 'SHORT':
        return 'short_open'
    elif row['side'] == 'BUY' and row['positionSide'] == 'SHORT':
        return 'short_close'
    else:
        return 'unknown'

df_final['Trade_Type'] = df_final.apply(classify_trade, axis=1)


ranking_df = df_final.groupby('Port_IDs').agg({
    'ROI': 'mean',
    'realizedProfit': 'sum',
    'Sharpe_Ratio': 'mean',
    'MDD': 'min',
    'Win_Rate': 'mean',
    'Win_Positions': 'max',
    'Total_Positions': 'max'
}).reset_index()

##  correlation matrix heatmap.

correlation_matrix = ranking_df.corr()
plt.figure(figsize=(8,6))
sns.heatmap(correlation_matrix, annot=True, cmap="coolwarm", fmt=".2f")
plt.title("Feature Correlation Matrix")
plt.show()

##scoring and ranking

WEIGHTS = {
    'ROI': 0.3,
    'Sharpe_Ratio': 0.2,
    'realizedProfit': 0.2,
    'Win_Rate': 0.1,
    'MDD': 0.1
}

# calculate scores.....
ranking_df['Score'] = (
    WEIGHTS['ROI'] * ranking_df['ROI'] +
    WEIGHTS['Sharpe_Ratio'] * ranking_df['Sharpe_Ratio'] +
    WEIGHTS['realizedProfit'] * ranking_df['realizedProfit'] +
    WEIGHTS['Win_Rate'] * ranking_df['Win_Rate'] +
    WEIGHTS['MDD'] * (1 - ranking_df['MDD'])
)

# rank accounts
ranking_df = ranking_df.sort_values(by='Score', ascending=False)

# top 20 accounts
top_20 = ranking_df.head(20)

#Summary Report

summary_report = ranking_df.describe().T
print(summary_report)

# Save Results

ranking_df.to_csv("calculated_metrics.csv", index=False)
top_20.to_csv("top_20_accounts.csv", index=False)
summary_report.to_csv("summary_report.csv")

feature_weights = {
    'ROI': 0.3,
    'Sharpe Ratio': 0.2,
    'PnL': 0.2,
    'Win Rate': 0.1,
    'MDD': 0.1
}

# convert to DataFrame
feature_weights_df = pd.DataFrame(list(feature_weights.items()), columns=['Feature', 'Weight'])

# Plot feature,
plt.figure(figsize=(8, 5))
sns.barplot(x=feature_weights_df['Feature'], y=feature_weights_df['Weight'], palette="viridis")
plt.title("Feature Importance in Scoring System")
plt.xlabel("Feature")
plt.ylabel("Weight")
plt.show()

df_final.to_csv("Trade_data.csv", index=False)

